#CHANGES TO THIS FILE WILL AUTOMATICALLY BE OVERWRITTEN
#This file is autogenerated by the zbxapi rakefile.
#This file contains the latest SVN revision number at the time
#the rakefile was run

ZBXAPI_VERSION="0.1"
ZBXAPI_REVISION="323"
